config/routes.rb
Rails.application.routes.draw do

  
  root 'home#index'

  namespace :admin do
      resources :users

      root to: "users#index"
    end

  resources :labs
  resources :questions
  resources :candidates
  resources :tests do
    post :approve
  end

  resources :attempts, only: [:show, :index]


  devise_for :users, path: 'users', controllers: { sessions: "users/sessions" , confirmations: 'confirmations' }

  
  
end

app/models/lab.rb
class Lab < ApplicationRecord
    has_many :candidates
    has_one :test
end

app/controllers/labs_controller.rb
class LabsController < ApplicationController
  def index
    @lab = Lab.all
  end

  def show
   @lab = Lab.find(params[:id])
  end

  def new
    @lab =Lab.new
  end

  def edit
    @lab = Lab.find(params[:id])
  end

  def create
    @lab = Lab.new(lab_params)
      if @lab.save
        redirect_to @lab, notice: 'Lab was successfully created.' 
      else
        redirect_to new_lab_path
      end
  end

  def update
    @lab = Lab.find_by(id: params[:id])
      if @lab.update_attributes(lab_params)
        redirect_to @lab, notice: 'Lab was successfully updated.'
      else
        render :edit 
      end
  end


  def destroy
    @lab = Lab.find(params[:id])
      if @lab.present?
        @lab.destroy
      end
      redirect_to labs_url, notice: 'Lab was successfully destroyed.' 
  end


  private
    def lab_params
      params.require(:lab).permit(:lab_name, :description, :starting_date)
    end

end

app/helpers/labs_helper.rb
module LabsHelper
end

app/views/labs/_form.html.erb
<%= form_for @lab do |f| %>

  <div class="field">
    <%= f.label :lab_name %>
    <%= f.text_field :lab_name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="field">
    <%= f.label :starting_date %>
    <%= f.text_field :starting_date %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/labs/edit.html.erb
<h3>Editing Lab</h3>

<%= render 'form', lab: @lab %>

<%= link_to 'Show', @lab %> |
<%= link_to 'Delete',  @lab,  method: :delete, data: { confirm: 'Are you sure?' } %> |
<%= link_to 'Back', labs_path %>

app/views/labs/index.html.erb
<div>
  <%= link_to 'New lab', new_lab_path %>
</div>

<div>
<% @lab.each do |lab| %>
<div class="card d-inline-block" style="width: 18rem;">
  <img class="card-img-top" src="https://www.thetrainingroom.com/getmedia/7ff5a360-83b7-49b7-bc66-01cc1d4d4438/2017-03-21-IT-coursesaspx?width=840&height=439" alt="Card image cap">
  <div class="card-body">
    <h5 class="card-title"><%= lab.lab_name %></h5>
    <p class="card-text"><%= lab.description %></p>
    <%= link_to 'Show more', lab_path(lab), class: "btn btn-primary"%>
  </div>
</div>
<% end %>

app/views/labs/new.html.erb
<h1>New Lab</h1>

<%= render 'form', lab: @lab %>



<%= link_to 'Back', labs_path %>

app/views/labs/show.html.erb
<h1><%=@lab.lab_name%></h1>
<h1><%=@lab.description%></h1>

<%= link_to 'Enroll', new_candidate_path(@candidate, lab_id: @lab.id), class: "btn btn-primary" %> |
<%= link_to 'Edit', edit_lab_path(@lab), class: "btn btn-primary" %> |
<%= link_to 'Back', :back, class: "btn btn-primary" %>